project:
  type: website

website:
  title: Drake Lab
  sidebar:
    - title: Research
      contents:
        - project-1.qmd
    - title: Teaching
      contents: 
        - course-1.qmd
    - contents:
        - index.qmd
        - about.qmd
    